defaults: &shareimage
  docker:
    - image: amazon/aws-cli
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  create_infrastructure_VPC:
    <<: *shareimage
    steps:
      - checkout
      - run: aws cloudformation create-stack --stack-name network-stack --region us-west-2 --template-body file://Udacitynetwork-vpc.yml --parameters file://udacityparameters.json
      - run: sleep 300

  create_infrastructure_server:
    <<: *shareimage
    steps:
      - checkout
      - run: aws cloudformation create-stack --stack-name servers-stack1 --region us-west-2 --template-body file://demoserver.yml --parameters file://demoservers.json
workflows:
  welcome:
    jobs:
      - create_infrastructure_VPC
      - create_infrastructure_server:
          requires:
            - create_infrastructure_VPC
      #- analyze:
      #    requires:
      #      - test
